namespace NexaSoft.Club.Domain.HumanResources.EmployeesInfo;

public sealed record EmployeeInfoResponse(
    long Id,
    string? EmployeeCode,
    long? UserId,
    string? FullName,
    string? Dni,
    long? PositionId,
    string? PositionCode,
    long? EmployeeTypeId,
    string? EmployeeTypeCode,
    long? DepartmentId,
    string? DepartamentCode,
    DateOnly HireDate,
    decimal BaseSalary,
    long? PaymentMethodId,
    string? PaymentMethodCode,
    long? BankId,
    string? BankCode,
    long? BankAccountTypeId,
    string? BankAccountCode,
    long? CurrencyId,
    string? CurrencyCode,
    string? BankAccountNumber,
    string? CciNumber,
    long? CompanyId,
    string? CompanyName,
    long? CostCenterId,
    string? CostCenterCode,
    bool? IsFamilyAllowance,
    long? ContractTypeId,
    string? ContractTypeCode,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    string? CreatedBy,
    string? UpdatedBy
);
