namespace NexaSoft.Agro.Domain.Masters.Consultoras.Colaboradores;

public sealed record ColaboradorResponse(
    long Id,
    string? NombresColaborador,
    string? ApellidosColaborador,
    string? NombreCompletoColaborador,
    string? TipoDocumento,
    string? NumeroDocumentoIdentidad,
    DateOnly? FechaNacimiento,
    string? Genero,
    string? EstadoCivil,
    string? Direccion,
    string? CorreoElectronico,
    string? TelefonoMovil,
    string? Cargo,
    string? Departamento,
    DateOnly? FechaIngreso,
    decimal? Salario,
    DateOnly? FechaCese,
    string? Comentarios,
    long ConsultoraId,
    string? NombreConsultora,
    string? UserName,
    int TipoDocumentoId,
    int GeneroColaboradorId,
    int EstadoCivilColaboradorId,
    int CargoId,
    int DepartamentoId,
    DateTime FechaCreacion,
    DateTime? FechaModificacion,
    string? UsuarioCreacion,
    string? UsuarioModificacion
);
