namespace NexaSoft.Club.Domain.Features.Members;

public sealed record MemberResponse(
    long Id,
    string? Dni,
    string? FirstName,
    string? LastName,
    string? Email,
    string? Phone,
    long DepartamentId,
    string? DepartamentName,
    long ProvinceId,
    string? ProvinceName,
    long DistrictId,
    string? DistrictName,
    string? Address,
    DateOnly? BirthDate,
    long MemberTypeId,
    string? TypeName,
    long MemberStatusId,
    string? StatusName,
    DateOnly JoinDate,
    DateOnly? ExpirationDate,
    decimal Balance,   
    bool EntryFeePaid,
    DateTime? LastPaymentDate,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    string? CreatedBy,
    string? UpdatedBy
);
